apiVersion: 1

policies:
  - orgId: 1
    receiver: noop
    group_by: ['alertname', 'severity', 'team']
    group_wait: 30s
    group_interval: 2m
    repeat_interval: 4h
    routes:
      - matchers:
          - severity = critical
        receiver: critical
        repeat_interval: 15m
      - matchers:
          - severity = warning
        receiver: warning
        repeat_interval: 1h
