global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "jambo-backend"
    static_configs:
      - targets: ["backend:8080"]
    metrics_path: /metrics

  - job_name: "jambo-ai-worker"
    static_configs:
      - targets: ["ai-worker:10080"]
    metrics_path: /metrics

  - job_name: "jambo-scheduler-worker"
    static_configs:
      - targets: ["scheduler-worker:9080"]
    metrics_path: /metrics
