apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jambo
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - redis.yaml
  - mailhog.yaml
  - backend.yaml
  - ai-worker.yaml
  - scheduler-worker.yaml
  - frontend.yaml
  - ingress.yaml
  - loki.yaml
  - promtail.yaml
  - tempo.yaml
  - grafana.yaml
  - alertmanager.yaml
  - prometheus.yaml
  - monitoring-nginx.yaml
